// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJyYHPbzcyxVlqmfSOsZXkD7ElXXJfMko',
    appId: '1:60257843578:web:39439b50407de1ee747ec3',
    messagingSenderId: '60257843578',
    projectId: 'tomoni-22782',
    authDomain: 'tomoni-22782.firebaseapp.com',
    storageBucket: 'tomoni-22782.firebasestorage.app',
    measurementId: 'G-Z8CRJNM2PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfS3SKYdIqwZDCiQY0AfV_9gSnOpSAOGc',
    appId: '1:60257843578:android:6622f1763def5d21747ec3',
    messagingSenderId: '60257843578',
    projectId: 'tomoni-22782',
    storageBucket: 'tomoni-22782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuEA6ApOYAejb0Y_EDRpWz-cmiFT1rq4',
    appId: '1:60257843578:ios:4db791da934fe85b747ec3',
    messagingSenderId: '60257843578',
    projectId: 'tomoni-22782',
    storageBucket: 'tomoni-22782.firebasestorage.app',
    iosBundleId: 'com.sm.tomoniFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuEA6ApOYAejb0Y_EDRpWz-cmiFT1rq4',
    appId: '1:60257843578:ios:aeb4d15ae7265100747ec3',
    messagingSenderId: '60257843578',
    projectId: 'tomoni-22782',
    storageBucket: 'tomoni-22782.firebasestorage.app',
    iosBundleId: 'com.example.tomoniFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJyYHPbzcyxVlqmfSOsZXkD7ElXXJfMko',
    appId: '1:60257843578:web:7051e0b70a37965d747ec3',
    messagingSenderId: '60257843578',
    projectId: 'tomoni-22782',
    authDomain: 'tomoni-22782.firebaseapp.com',
    storageBucket: 'tomoni-22782.firebasestorage.app',
    measurementId: 'G-2KQVVTM9SL',
  );
}
